#!/bin/bash
# helper script for converting the README.md to rst format before running
# setup.py

# utility function to test whether a given command exists
command_exists () {
    command -v $1 >/dev/null 2>&1 ;
}

HOSTNAME=`hostname`

if [[ $HOSTNAME = bragg-l || $HOSTNAME = bragg-l-test ]]; then
    module load pandoc
fi

if command_exists pandoc ; then
    echo 'Converting README.md to rst format ...'
    pandoc -o README.rst README.md
else
    echo '*** README.md not converted to rst: pandoc not found ***'
fi

echo 'Installing sambuca in' $1 'mode'
python setup.py $1
